Param(
    $domainNet,
    $vagrantUsername
)

New-Item -ItemType File -Path "C:\office\ConfigurationFile2016.ini" -Force

$sqlConfigFile = "C:\office\ConfigurationFile2016.ini"


$sw = [Diagnostics.Stopwatch]::StartNew()

Set-Content $sqlConfigFile -Force -Value '; SQL Server 2016 Configuration File'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '[OPTIONS]'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies a Setup work flow, like INSTALL, UNINSTALL, or UPGRADE. This is a required parameter. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'ACTION="Install"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies that SQL Server Setup should not display the privacy statement when ran from the command line. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SUPPRESSPRIVACYSTATEMENTNOTICE="False"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; By specifying this parameter and accepting Microsoft R Open and Microsoft R Server terms, you acknowledge that you have read and understood the terms of use. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'IACCEPTROPENLICENSETERMS="False"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Use the /ENU parameter to install the English version of SQL Server on your localized Windows operating system. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'ENU="True"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify whether SQL Server Setup should discover and include product updates. The valid values are True and False or 1 and 0. By default SQL Server Setup will include updates that are found. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'UpdateEnabled="False"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify the location where SQL Server Setup will obtain product updates. The valid values are "MU" to search Microsoft Update, a valid folder path, a relative path such as .\MyUpdates or a UNC share. By default SQL Server Setup will search Microsoft Update or a Windows Update service through the Window Server Update Services. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'UpdateSource="MU"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies features to install, uninstall, or upgrade. The list of top-level features include SQL, AS, IS, MDS, and Tools. The SQL feature will install the Database Engine, Replication, Full-Text, and Data Quality Services (DQS) server. The Tools feature will install shared components. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'FEATURES=SQL,RS,Tools'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Displays the command line parameters usage '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'HELP="False"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies that the detailed Setup log should be piped to the console. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'INDICATEPROGRESS="False"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify a default or named instance. MSSQLSERVER is the default instance for non-Express editions and SQLExpress for Express editions. This parameter is required when installing the SQL Server Database Engine (SQL), or Analysis Services (AS). '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'INSTANCENAME="MSSQLSERVER"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify the root installation directory for shared components.  This directory remains unchanged after shared components are already installed. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify the root installation directory for the WOW64 shared components.  This directory remains unchanged after WOW64 shared components are already installed. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify the Instance ID for the SQL Server features you have specified. SQL Server directory structure, registry structure, and service names will incorporate the instance ID of the SQL Server instance. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'INSTANCEID="MSSQLSERVER"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify the installation directory. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'INSTANCEDIR="C:\Program Files\Microsoft SQL Server"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Agent account name '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'AGTSVCACCOUNT="NT Authority\System"'
#Add-Content $sqlConfigFile -Value 'AGTSVCPASSWORD=""'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Auto-start service after installation.  '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'AGTSVCSTARTUPTYPE="Automatic"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Startup type for the SQL Server service. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLSVCSTARTUPTYPE="Automatic"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Startup type for the SQL Server service. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'RSSVCSTARTUPTYPE="Automatic"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Level to enable FILESTREAM feature at (0, 1, 2 or 3). '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'FILESTREAMLEVEL="0"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Set to "1" to enable RANU for SQL Server Express. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'ENABLERANU="False"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies a Windows collation or an SQL collation to use for the Database Engine. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLCOLLATION="Latin1_General_CI_AS"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Account for SQL Server service: Domain\User or system account. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLSVCACCOUNT="NT Authority\Network Service"'
#Add-Content $sqlConfigFile -Value 'SQLSVCPASSWORD=""'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Set to "True" to enable instant file initialization for SQL Server service. If enabled, Setup will grant Perform Volume Maintenance Task privilege to the Database Engine Service SID. This may lead to information disclosure as it could allow deleted content to be accessed by an unauthorized principal. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLSVCINSTANTFILEINIT="True"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Windows account(s) to provision as SQL Server system administrators. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value "SQLSYSADMINACCOUNTS=`"$domainNet\$vagrantUsername`" `"$domainNet\SQLAccessGroup`" `"$vagrantUsername`" `"BUILTIN\Administrators`""
Add-Content $sqlConfigFile -Value 'RSSVCACCOUNT="NT Authority\Network Service"'
#Add-Content $sqlConfigFile -Value 'RSSVCPASSWORD=""'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Windows account(s) to provision as SQL Server system administrators. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value "ASSYSADMINACCOUNTS=`"$domainNet\$vagrantUsername`" `"$domainNet\SQLAccessGroup`" `"$vagrantUsername`" `"BUILTIN\Administrators`""
Add-Content $sqlConfigFile -Value 'ISSVCACCOUNT="NT Authority\System"'
Add-Content $sqlConfigFile -Value 'ASSVCACCOUNT="NT Authority\System"'
#Add-Content $sqlConfigFile -Value 'ASSVCPASSWORD=""'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; The number of Database Engine TempDB files. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLTEMPDBFILECOUNT="8"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies the initial size of a Database Engine TempDB data file in MB. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLTEMPDBFILESIZE="8"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies the automatic growth increment of each Database Engine TempDB data file in MB. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLTEMPDBFILEGROWTH="64"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies the initial size of the Database Engine TempDB log file in MB. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLTEMPDBLOGFILESIZE="8"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specifies the automatic growth increment of the Database Engine TempDB log file in MB. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'SQLTEMPDBLOGFILEGROWTH="64"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Provision current user as a Database Engine system administrator for %SQL_PRODUCT_SHORT_NAME% Express. '
Add-Content $sqlConfigFile -Value ''
#Add-Content $sqlConfigFile -Value 'ADDCURRENTUSERASSQLADMIN="True"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify 0 to disable or 1 to enable the TCP/IP protocol. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'TCPENABLED="1"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Specify 0 to disable or 1 to enable the Named Pipes protocol. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'NPENABLED="1"'
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value '; Startup type for Browser Service. '
Add-Content $sqlConfigFile -Value ''
Add-Content $sqlConfigFile -Value 'BROWSERSVCSTARTUPTYPE="Disabled"'
Add-Content $sqlConfigFile -Value ''

#print Time taken to execute
$sw.Stop()
"Sql Config Script Creation Completed in {0:c}" -f $sw.Elapsed;